version: '3'

services:
  wp:
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    hostname: ${HOSTNAME}
    depends_on:
      - wpdb
    ports:
      - ${PORT}:80
    volumes:
      - ./src/theme:/var/www/html/wp-content/themes/theme
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_PASSWORD: wordpress

  wpdb:
    image: mysql:${MYSQL_VERSION}
    restart: always
    user: "1000:50"
    volumes:
      - ./data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    hostname: admin.${HOSTNAME}
    depends_on:
      - wpdb
