version: '3'

services:
  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    user: "1000:50"
    volumes:
      - ./data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"

  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src/theme:/var/www/html/wp-content/themes/theme
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
